-- this is generated by luajitffi
local ffi = require('ffi')
---@type Table<string, integer>
local C = ffi.C

local M = {
    libs = {},
    cache = {},
}

-- cdef
require('imgui_ffi.cdef.imgui_impl_opengl3')
require('imgui_ffi.cdef.gl')
require('imgui_ffi.cdef.imgui_impl_glfw')
require('imgui_ffi.cdef.vcruntime')
require('imgui_ffi.cdef.imgui')
require('imgui_ffi.cdef.vadefs')
M.enums = {
    ImGuiWindowFlags_ = {
        ImGuiWindowFlags_None = C.ImGuiWindowFlags_None,
        ImGuiWindowFlags_NoTitleBar = C.ImGuiWindowFlags_NoTitleBar,
        ImGuiWindowFlags_NoResize = C.ImGuiWindowFlags_NoResize,
        ImGuiWindowFlags_NoMove = C.ImGuiWindowFlags_NoMove,
        ImGuiWindowFlags_NoScrollbar = C.ImGuiWindowFlags_NoScrollbar,
        ImGuiWindowFlags_NoScrollWithMouse = C.ImGuiWindowFlags_NoScrollWithMouse,
        ImGuiWindowFlags_NoCollapse = C.ImGuiWindowFlags_NoCollapse,
        ImGuiWindowFlags_AlwaysAutoResize = C.ImGuiWindowFlags_AlwaysAutoResize,
        ImGuiWindowFlags_NoBackground = C.ImGuiWindowFlags_NoBackground,
        ImGuiWindowFlags_NoSavedSettings = C.ImGuiWindowFlags_NoSavedSettings,
        ImGuiWindowFlags_NoMouseInputs = C.ImGuiWindowFlags_NoMouseInputs,
        ImGuiWindowFlags_MenuBar = C.ImGuiWindowFlags_MenuBar,
        ImGuiWindowFlags_HorizontalScrollbar = C.ImGuiWindowFlags_HorizontalScrollbar,
        ImGuiWindowFlags_NoFocusOnAppearing = C.ImGuiWindowFlags_NoFocusOnAppearing,
        ImGuiWindowFlags_NoBringToFrontOnFocus = C.ImGuiWindowFlags_NoBringToFrontOnFocus,
        ImGuiWindowFlags_AlwaysVerticalScrollbar = C.ImGuiWindowFlags_AlwaysVerticalScrollbar,
        ImGuiWindowFlags_AlwaysHorizontalScrollbar = C.ImGuiWindowFlags_AlwaysHorizontalScrollbar,
        ImGuiWindowFlags_AlwaysUseWindowPadding = C.ImGuiWindowFlags_AlwaysUseWindowPadding,
        ImGuiWindowFlags_NoNavInputs = C.ImGuiWindowFlags_NoNavInputs,
        ImGuiWindowFlags_NoNavFocus = C.ImGuiWindowFlags_NoNavFocus,
        ImGuiWindowFlags_UnsavedDocument = C.ImGuiWindowFlags_UnsavedDocument,
        ImGuiWindowFlags_NoNav = C.ImGuiWindowFlags_NoNav,
        ImGuiWindowFlags_NoDecoration = C.ImGuiWindowFlags_NoDecoration,
        ImGuiWindowFlags_NoInputs = C.ImGuiWindowFlags_NoInputs,
        ImGuiWindowFlags_NavFlattened = C.ImGuiWindowFlags_NavFlattened,
        ImGuiWindowFlags_ChildWindow = C.ImGuiWindowFlags_ChildWindow,
        ImGuiWindowFlags_Tooltip = C.ImGuiWindowFlags_Tooltip,
        ImGuiWindowFlags_Popup = C.ImGuiWindowFlags_Popup,
        ImGuiWindowFlags_Modal = C.ImGuiWindowFlags_Modal,
        ImGuiWindowFlags_ChildMenu = C.ImGuiWindowFlags_ChildMenu,
    },
    ImGuiInputTextFlags_ = {
        ImGuiInputTextFlags_None = C.ImGuiInputTextFlags_None,
        ImGuiInputTextFlags_CharsDecimal = C.ImGuiInputTextFlags_CharsDecimal,
        ImGuiInputTextFlags_CharsHexadecimal = C.ImGuiInputTextFlags_CharsHexadecimal,
        ImGuiInputTextFlags_CharsUppercase = C.ImGuiInputTextFlags_CharsUppercase,
        ImGuiInputTextFlags_CharsNoBlank = C.ImGuiInputTextFlags_CharsNoBlank,
        ImGuiInputTextFlags_AutoSelectAll = C.ImGuiInputTextFlags_AutoSelectAll,
        ImGuiInputTextFlags_EnterReturnsTrue = C.ImGuiInputTextFlags_EnterReturnsTrue,
        ImGuiInputTextFlags_CallbackCompletion = C.ImGuiInputTextFlags_CallbackCompletion,
        ImGuiInputTextFlags_CallbackHistory = C.ImGuiInputTextFlags_CallbackHistory,
        ImGuiInputTextFlags_CallbackAlways = C.ImGuiInputTextFlags_CallbackAlways,
        ImGuiInputTextFlags_CallbackCharFilter = C.ImGuiInputTextFlags_CallbackCharFilter,
        ImGuiInputTextFlags_AllowTabInput = C.ImGuiInputTextFlags_AllowTabInput,
        ImGuiInputTextFlags_CtrlEnterForNewLine = C.ImGuiInputTextFlags_CtrlEnterForNewLine,
        ImGuiInputTextFlags_NoHorizontalScroll = C.ImGuiInputTextFlags_NoHorizontalScroll,
        ImGuiInputTextFlags_AlwaysOverwrite = C.ImGuiInputTextFlags_AlwaysOverwrite,
        ImGuiInputTextFlags_ReadOnly = C.ImGuiInputTextFlags_ReadOnly,
        ImGuiInputTextFlags_Password = C.ImGuiInputTextFlags_Password,
        ImGuiInputTextFlags_NoUndoRedo = C.ImGuiInputTextFlags_NoUndoRedo,
        ImGuiInputTextFlags_CharsScientific = C.ImGuiInputTextFlags_CharsScientific,
        ImGuiInputTextFlags_CallbackResize = C.ImGuiInputTextFlags_CallbackResize,
        ImGuiInputTextFlags_CallbackEdit = C.ImGuiInputTextFlags_CallbackEdit,
        ImGuiInputTextFlags_AlwaysInsertMode = C.ImGuiInputTextFlags_AlwaysInsertMode,
    },
    ImGuiTreeNodeFlags_ = {
        ImGuiTreeNodeFlags_None = C.ImGuiTreeNodeFlags_None,
        ImGuiTreeNodeFlags_Selected = C.ImGuiTreeNodeFlags_Selected,
        ImGuiTreeNodeFlags_Framed = C.ImGuiTreeNodeFlags_Framed,
        ImGuiTreeNodeFlags_AllowItemOverlap = C.ImGuiTreeNodeFlags_AllowItemOverlap,
        ImGuiTreeNodeFlags_NoTreePushOnOpen = C.ImGuiTreeNodeFlags_NoTreePushOnOpen,
        ImGuiTreeNodeFlags_NoAutoOpenOnLog = C.ImGuiTreeNodeFlags_NoAutoOpenOnLog,
        ImGuiTreeNodeFlags_DefaultOpen = C.ImGuiTreeNodeFlags_DefaultOpen,
        ImGuiTreeNodeFlags_OpenOnDoubleClick = C.ImGuiTreeNodeFlags_OpenOnDoubleClick,
        ImGuiTreeNodeFlags_OpenOnArrow = C.ImGuiTreeNodeFlags_OpenOnArrow,
        ImGuiTreeNodeFlags_Leaf = C.ImGuiTreeNodeFlags_Leaf,
        ImGuiTreeNodeFlags_Bullet = C.ImGuiTreeNodeFlags_Bullet,
        ImGuiTreeNodeFlags_FramePadding = C.ImGuiTreeNodeFlags_FramePadding,
        ImGuiTreeNodeFlags_SpanAvailWidth = C.ImGuiTreeNodeFlags_SpanAvailWidth,
        ImGuiTreeNodeFlags_SpanFullWidth = C.ImGuiTreeNodeFlags_SpanFullWidth,
        ImGuiTreeNodeFlags_NavLeftJumpsBackHere = C.ImGuiTreeNodeFlags_NavLeftJumpsBackHere,
        ImGuiTreeNodeFlags_CollapsingHeader = C.ImGuiTreeNodeFlags_CollapsingHeader,
    },
    ImGuiPopupFlags_ = {
        ImGuiPopupFlags_None = C.ImGuiPopupFlags_None,
        ImGuiPopupFlags_MouseButtonLeft = C.ImGuiPopupFlags_MouseButtonLeft,
        ImGuiPopupFlags_MouseButtonRight = C.ImGuiPopupFlags_MouseButtonRight,
        ImGuiPopupFlags_MouseButtonMiddle = C.ImGuiPopupFlags_MouseButtonMiddle,
        ImGuiPopupFlags_MouseButtonMask_ = C.ImGuiPopupFlags_MouseButtonMask_,
        ImGuiPopupFlags_MouseButtonDefault_ = C.ImGuiPopupFlags_MouseButtonDefault_,
        ImGuiPopupFlags_NoOpenOverExistingPopup = C.ImGuiPopupFlags_NoOpenOverExistingPopup,
        ImGuiPopupFlags_NoOpenOverItems = C.ImGuiPopupFlags_NoOpenOverItems,
        ImGuiPopupFlags_AnyPopupId = C.ImGuiPopupFlags_AnyPopupId,
        ImGuiPopupFlags_AnyPopupLevel = C.ImGuiPopupFlags_AnyPopupLevel,
        ImGuiPopupFlags_AnyPopup = C.ImGuiPopupFlags_AnyPopup,
    },
    ImGuiSelectableFlags_ = {
        ImGuiSelectableFlags_None = C.ImGuiSelectableFlags_None,
        ImGuiSelectableFlags_DontClosePopups = C.ImGuiSelectableFlags_DontClosePopups,
        ImGuiSelectableFlags_SpanAllColumns = C.ImGuiSelectableFlags_SpanAllColumns,
        ImGuiSelectableFlags_AllowDoubleClick = C.ImGuiSelectableFlags_AllowDoubleClick,
        ImGuiSelectableFlags_Disabled = C.ImGuiSelectableFlags_Disabled,
        ImGuiSelectableFlags_AllowItemOverlap = C.ImGuiSelectableFlags_AllowItemOverlap,
    },
    ImGuiComboFlags_ = {
        ImGuiComboFlags_None = C.ImGuiComboFlags_None,
        ImGuiComboFlags_PopupAlignLeft = C.ImGuiComboFlags_PopupAlignLeft,
        ImGuiComboFlags_HeightSmall = C.ImGuiComboFlags_HeightSmall,
        ImGuiComboFlags_HeightRegular = C.ImGuiComboFlags_HeightRegular,
        ImGuiComboFlags_HeightLarge = C.ImGuiComboFlags_HeightLarge,
        ImGuiComboFlags_HeightLargest = C.ImGuiComboFlags_HeightLargest,
        ImGuiComboFlags_NoArrowButton = C.ImGuiComboFlags_NoArrowButton,
        ImGuiComboFlags_NoPreview = C.ImGuiComboFlags_NoPreview,
        ImGuiComboFlags_HeightMask_ = C.ImGuiComboFlags_HeightMask_,
    },
    ImGuiTabBarFlags_ = {
        ImGuiTabBarFlags_None = C.ImGuiTabBarFlags_None,
        ImGuiTabBarFlags_Reorderable = C.ImGuiTabBarFlags_Reorderable,
        ImGuiTabBarFlags_AutoSelectNewTabs = C.ImGuiTabBarFlags_AutoSelectNewTabs,
        ImGuiTabBarFlags_TabListPopupButton = C.ImGuiTabBarFlags_TabListPopupButton,
        ImGuiTabBarFlags_NoCloseWithMiddleMouseButton = C.ImGuiTabBarFlags_NoCloseWithMiddleMouseButton,
        ImGuiTabBarFlags_NoTabListScrollingButtons = C.ImGuiTabBarFlags_NoTabListScrollingButtons,
        ImGuiTabBarFlags_NoTooltip = C.ImGuiTabBarFlags_NoTooltip,
        ImGuiTabBarFlags_FittingPolicyResizeDown = C.ImGuiTabBarFlags_FittingPolicyResizeDown,
        ImGuiTabBarFlags_FittingPolicyScroll = C.ImGuiTabBarFlags_FittingPolicyScroll,
        ImGuiTabBarFlags_FittingPolicyMask_ = C.ImGuiTabBarFlags_FittingPolicyMask_,
        ImGuiTabBarFlags_FittingPolicyDefault_ = C.ImGuiTabBarFlags_FittingPolicyDefault_,
    },
    ImGuiTabItemFlags_ = {
        ImGuiTabItemFlags_None = C.ImGuiTabItemFlags_None,
        ImGuiTabItemFlags_UnsavedDocument = C.ImGuiTabItemFlags_UnsavedDocument,
        ImGuiTabItemFlags_SetSelected = C.ImGuiTabItemFlags_SetSelected,
        ImGuiTabItemFlags_NoCloseWithMiddleMouseButton = C.ImGuiTabItemFlags_NoCloseWithMiddleMouseButton,
        ImGuiTabItemFlags_NoPushId = C.ImGuiTabItemFlags_NoPushId,
        ImGuiTabItemFlags_NoTooltip = C.ImGuiTabItemFlags_NoTooltip,
        ImGuiTabItemFlags_NoReorder = C.ImGuiTabItemFlags_NoReorder,
        ImGuiTabItemFlags_Leading = C.ImGuiTabItemFlags_Leading,
        ImGuiTabItemFlags_Trailing = C.ImGuiTabItemFlags_Trailing,
    },
    ImGuiTableFlags_ = {
        ImGuiTableFlags_None = C.ImGuiTableFlags_None,
        ImGuiTableFlags_Resizable = C.ImGuiTableFlags_Resizable,
        ImGuiTableFlags_Reorderable = C.ImGuiTableFlags_Reorderable,
        ImGuiTableFlags_Hideable = C.ImGuiTableFlags_Hideable,
        ImGuiTableFlags_Sortable = C.ImGuiTableFlags_Sortable,
        ImGuiTableFlags_NoSavedSettings = C.ImGuiTableFlags_NoSavedSettings,
        ImGuiTableFlags_ContextMenuInBody = C.ImGuiTableFlags_ContextMenuInBody,
        ImGuiTableFlags_RowBg = C.ImGuiTableFlags_RowBg,
        ImGuiTableFlags_BordersInnerH = C.ImGuiTableFlags_BordersInnerH,
        ImGuiTableFlags_BordersOuterH = C.ImGuiTableFlags_BordersOuterH,
        ImGuiTableFlags_BordersInnerV = C.ImGuiTableFlags_BordersInnerV,
        ImGuiTableFlags_BordersOuterV = C.ImGuiTableFlags_BordersOuterV,
        ImGuiTableFlags_BordersH = C.ImGuiTableFlags_BordersH,
        ImGuiTableFlags_BordersV = C.ImGuiTableFlags_BordersV,
        ImGuiTableFlags_BordersInner = C.ImGuiTableFlags_BordersInner,
        ImGuiTableFlags_BordersOuter = C.ImGuiTableFlags_BordersOuter,
        ImGuiTableFlags_Borders = C.ImGuiTableFlags_Borders,
        ImGuiTableFlags_NoBordersInBody = C.ImGuiTableFlags_NoBordersInBody,
        ImGuiTableFlags_NoBordersInBodyUntilResize = C.ImGuiTableFlags_NoBordersInBodyUntilResize,
        ImGuiTableFlags_SizingFixedFit = C.ImGuiTableFlags_SizingFixedFit,
        ImGuiTableFlags_SizingFixedSame = C.ImGuiTableFlags_SizingFixedSame,
        ImGuiTableFlags_SizingStretchProp = C.ImGuiTableFlags_SizingStretchProp,
        ImGuiTableFlags_SizingStretchSame = C.ImGuiTableFlags_SizingStretchSame,
        ImGuiTableFlags_NoHostExtendX = C.ImGuiTableFlags_NoHostExtendX,
        ImGuiTableFlags_NoHostExtendY = C.ImGuiTableFlags_NoHostExtendY,
        ImGuiTableFlags_NoKeepColumnsVisible = C.ImGuiTableFlags_NoKeepColumnsVisible,
        ImGuiTableFlags_PreciseWidths = C.ImGuiTableFlags_PreciseWidths,
        ImGuiTableFlags_NoClip = C.ImGuiTableFlags_NoClip,
        ImGuiTableFlags_PadOuterX = C.ImGuiTableFlags_PadOuterX,
        ImGuiTableFlags_NoPadOuterX = C.ImGuiTableFlags_NoPadOuterX,
        ImGuiTableFlags_NoPadInnerX = C.ImGuiTableFlags_NoPadInnerX,
        ImGuiTableFlags_ScrollX = C.ImGuiTableFlags_ScrollX,
        ImGuiTableFlags_ScrollY = C.ImGuiTableFlags_ScrollY,
        ImGuiTableFlags_SortMulti = C.ImGuiTableFlags_SortMulti,
        ImGuiTableFlags_SortTristate = C.ImGuiTableFlags_SortTristate,
        ImGuiTableFlags_SizingMask_ = C.ImGuiTableFlags_SizingMask_,
    },
    ImGuiTableColumnFlags_ = {
        ImGuiTableColumnFlags_None = C.ImGuiTableColumnFlags_None,
        ImGuiTableColumnFlags_Disabled = C.ImGuiTableColumnFlags_Disabled,
        ImGuiTableColumnFlags_DefaultHide = C.ImGuiTableColumnFlags_DefaultHide,
        ImGuiTableColumnFlags_DefaultSort = C.ImGuiTableColumnFlags_DefaultSort,
        ImGuiTableColumnFlags_WidthStretch = C.ImGuiTableColumnFlags_WidthStretch,
        ImGuiTableColumnFlags_WidthFixed = C.ImGuiTableColumnFlags_WidthFixed,
        ImGuiTableColumnFlags_NoResize = C.ImGuiTableColumnFlags_NoResize,
        ImGuiTableColumnFlags_NoReorder = C.ImGuiTableColumnFlags_NoReorder,
        ImGuiTableColumnFlags_NoHide = C.ImGuiTableColumnFlags_NoHide,
        ImGuiTableColumnFlags_NoClip = C.ImGuiTableColumnFlags_NoClip,
        ImGuiTableColumnFlags_NoSort = C.ImGuiTableColumnFlags_NoSort,
        ImGuiTableColumnFlags_NoSortAscending = C.ImGuiTableColumnFlags_NoSortAscending,
        ImGuiTableColumnFlags_NoSortDescending = C.ImGuiTableColumnFlags_NoSortDescending,
        ImGuiTableColumnFlags_NoHeaderLabel = C.ImGuiTableColumnFlags_NoHeaderLabel,
        ImGuiTableColumnFlags_NoHeaderWidth = C.ImGuiTableColumnFlags_NoHeaderWidth,
        ImGuiTableColumnFlags_PreferSortAscending = C.ImGuiTableColumnFlags_PreferSortAscending,
        ImGuiTableColumnFlags_PreferSortDescending = C.ImGuiTableColumnFlags_PreferSortDescending,
        ImGuiTableColumnFlags_IndentEnable = C.ImGuiTableColumnFlags_IndentEnable,
        ImGuiTableColumnFlags_IndentDisable = C.ImGuiTableColumnFlags_IndentDisable,
        ImGuiTableColumnFlags_IsEnabled = C.ImGuiTableColumnFlags_IsEnabled,
        ImGuiTableColumnFlags_IsVisible = C.ImGuiTableColumnFlags_IsVisible,
        ImGuiTableColumnFlags_IsSorted = C.ImGuiTableColumnFlags_IsSorted,
        ImGuiTableColumnFlags_IsHovered = C.ImGuiTableColumnFlags_IsHovered,
        ImGuiTableColumnFlags_WidthMask_ = C.ImGuiTableColumnFlags_WidthMask_,
        ImGuiTableColumnFlags_IndentMask_ = C.ImGuiTableColumnFlags_IndentMask_,
        ImGuiTableColumnFlags_StatusMask_ = C.ImGuiTableColumnFlags_StatusMask_,
        ImGuiTableColumnFlags_NoDirectResize_ = C.ImGuiTableColumnFlags_NoDirectResize_,
    },
    ImGuiTableRowFlags_ = {
        ImGuiTableRowFlags_None = C.ImGuiTableRowFlags_None,
        ImGuiTableRowFlags_Headers = C.ImGuiTableRowFlags_Headers,
    },
    ImGuiTableBgTarget_ = {
        ImGuiTableBgTarget_None = C.ImGuiTableBgTarget_None,
        ImGuiTableBgTarget_RowBg0 = C.ImGuiTableBgTarget_RowBg0,
        ImGuiTableBgTarget_RowBg1 = C.ImGuiTableBgTarget_RowBg1,
        ImGuiTableBgTarget_CellBg = C.ImGuiTableBgTarget_CellBg,
    },
    ImGuiFocusedFlags_ = {
        ImGuiFocusedFlags_None = C.ImGuiFocusedFlags_None,
        ImGuiFocusedFlags_ChildWindows = C.ImGuiFocusedFlags_ChildWindows,
        ImGuiFocusedFlags_RootWindow = C.ImGuiFocusedFlags_RootWindow,
        ImGuiFocusedFlags_AnyWindow = C.ImGuiFocusedFlags_AnyWindow,
        ImGuiFocusedFlags_RootAndChildWindows = C.ImGuiFocusedFlags_RootAndChildWindows,
    },
    ImGuiHoveredFlags_ = {
        ImGuiHoveredFlags_None = C.ImGuiHoveredFlags_None,
        ImGuiHoveredFlags_ChildWindows = C.ImGuiHoveredFlags_ChildWindows,
        ImGuiHoveredFlags_RootWindow = C.ImGuiHoveredFlags_RootWindow,
        ImGuiHoveredFlags_AnyWindow = C.ImGuiHoveredFlags_AnyWindow,
        ImGuiHoveredFlags_AllowWhenBlockedByPopup = C.ImGuiHoveredFlags_AllowWhenBlockedByPopup,
        ImGuiHoveredFlags_AllowWhenBlockedByActiveItem = C.ImGuiHoveredFlags_AllowWhenBlockedByActiveItem,
        ImGuiHoveredFlags_AllowWhenOverlapped = C.ImGuiHoveredFlags_AllowWhenOverlapped,
        ImGuiHoveredFlags_AllowWhenDisabled = C.ImGuiHoveredFlags_AllowWhenDisabled,
        ImGuiHoveredFlags_RectOnly = C.ImGuiHoveredFlags_RectOnly,
        ImGuiHoveredFlags_RootAndChildWindows = C.ImGuiHoveredFlags_RootAndChildWindows,
    },
    ImGuiDragDropFlags_ = {
        ImGuiDragDropFlags_None = C.ImGuiDragDropFlags_None,
        ImGuiDragDropFlags_SourceNoPreviewTooltip = C.ImGuiDragDropFlags_SourceNoPreviewTooltip,
        ImGuiDragDropFlags_SourceNoDisableHover = C.ImGuiDragDropFlags_SourceNoDisableHover,
        ImGuiDragDropFlags_SourceNoHoldToOpenOthers = C.ImGuiDragDropFlags_SourceNoHoldToOpenOthers,
        ImGuiDragDropFlags_SourceAllowNullID = C.ImGuiDragDropFlags_SourceAllowNullID,
        ImGuiDragDropFlags_SourceExtern = C.ImGuiDragDropFlags_SourceExtern,
        ImGuiDragDropFlags_SourceAutoExpirePayload = C.ImGuiDragDropFlags_SourceAutoExpirePayload,
        ImGuiDragDropFlags_AcceptBeforeDelivery = C.ImGuiDragDropFlags_AcceptBeforeDelivery,
        ImGuiDragDropFlags_AcceptNoDrawDefaultRect = C.ImGuiDragDropFlags_AcceptNoDrawDefaultRect,
        ImGuiDragDropFlags_AcceptNoPreviewTooltip = C.ImGuiDragDropFlags_AcceptNoPreviewTooltip,
        ImGuiDragDropFlags_AcceptPeekOnly = C.ImGuiDragDropFlags_AcceptPeekOnly,
    },
    ImGuiDataType_ = {
        ImGuiDataType_S8 = C.ImGuiDataType_S8,
        ImGuiDataType_U8 = C.ImGuiDataType_U8,
        ImGuiDataType_S16 = C.ImGuiDataType_S16,
        ImGuiDataType_U16 = C.ImGuiDataType_U16,
        ImGuiDataType_S32 = C.ImGuiDataType_S32,
        ImGuiDataType_U32 = C.ImGuiDataType_U32,
        ImGuiDataType_S64 = C.ImGuiDataType_S64,
        ImGuiDataType_U64 = C.ImGuiDataType_U64,
        ImGuiDataType_Float = C.ImGuiDataType_Float,
        ImGuiDataType_Double = C.ImGuiDataType_Double,
        ImGuiDataType_COUNT = C.ImGuiDataType_COUNT,
    },
    ImGuiDir_ = {
        ImGuiDir_None = C.ImGuiDir_None,
        ImGuiDir_Left = C.ImGuiDir_Left,
        ImGuiDir_Right = C.ImGuiDir_Right,
        ImGuiDir_Up = C.ImGuiDir_Up,
        ImGuiDir_Down = C.ImGuiDir_Down,
        ImGuiDir_COUNT = C.ImGuiDir_COUNT,
    },
    ImGuiSortDirection_ = {
        ImGuiSortDirection_None = C.ImGuiSortDirection_None,
        ImGuiSortDirection_Ascending = C.ImGuiSortDirection_Ascending,
        ImGuiSortDirection_Descending = C.ImGuiSortDirection_Descending,
    },
    ImGuiKey_ = {
        ImGuiKey_Tab = C.ImGuiKey_Tab,
        ImGuiKey_LeftArrow = C.ImGuiKey_LeftArrow,
        ImGuiKey_RightArrow = C.ImGuiKey_RightArrow,
        ImGuiKey_UpArrow = C.ImGuiKey_UpArrow,
        ImGuiKey_DownArrow = C.ImGuiKey_DownArrow,
        ImGuiKey_PageUp = C.ImGuiKey_PageUp,
        ImGuiKey_PageDown = C.ImGuiKey_PageDown,
        ImGuiKey_Home = C.ImGuiKey_Home,
        ImGuiKey_End = C.ImGuiKey_End,
        ImGuiKey_Insert = C.ImGuiKey_Insert,
        ImGuiKey_Delete = C.ImGuiKey_Delete,
        ImGuiKey_Backspace = C.ImGuiKey_Backspace,
        ImGuiKey_Space = C.ImGuiKey_Space,
        ImGuiKey_Enter = C.ImGuiKey_Enter,
        ImGuiKey_Escape = C.ImGuiKey_Escape,
        ImGuiKey_KeyPadEnter = C.ImGuiKey_KeyPadEnter,
        ImGuiKey_A = C.ImGuiKey_A,
        ImGuiKey_C = C.ImGuiKey_C,
        ImGuiKey_V = C.ImGuiKey_V,
        ImGuiKey_X = C.ImGuiKey_X,
        ImGuiKey_Y = C.ImGuiKey_Y,
        ImGuiKey_Z = C.ImGuiKey_Z,
        ImGuiKey_COUNT = C.ImGuiKey_COUNT,
    },
    ImGuiKeyModFlags_ = {
        ImGuiKeyModFlags_None = C.ImGuiKeyModFlags_None,
        ImGuiKeyModFlags_Ctrl = C.ImGuiKeyModFlags_Ctrl,
        ImGuiKeyModFlags_Shift = C.ImGuiKeyModFlags_Shift,
        ImGuiKeyModFlags_Alt = C.ImGuiKeyModFlags_Alt,
        ImGuiKeyModFlags_Super = C.ImGuiKeyModFlags_Super,
    },
    ImGuiNavInput_ = {
        ImGuiNavInput_Activate = C.ImGuiNavInput_Activate,
        ImGuiNavInput_Cancel = C.ImGuiNavInput_Cancel,
        ImGuiNavInput_Input = C.ImGuiNavInput_Input,
        ImGuiNavInput_Menu = C.ImGuiNavInput_Menu,
        ImGuiNavInput_DpadLeft = C.ImGuiNavInput_DpadLeft,
        ImGuiNavInput_DpadRight = C.ImGuiNavInput_DpadRight,
        ImGuiNavInput_DpadUp = C.ImGuiNavInput_DpadUp,
        ImGuiNavInput_DpadDown = C.ImGuiNavInput_DpadDown,
        ImGuiNavInput_LStickLeft = C.ImGuiNavInput_LStickLeft,
        ImGuiNavInput_LStickRight = C.ImGuiNavInput_LStickRight,
        ImGuiNavInput_LStickUp = C.ImGuiNavInput_LStickUp,
        ImGuiNavInput_LStickDown = C.ImGuiNavInput_LStickDown,
        ImGuiNavInput_FocusPrev = C.ImGuiNavInput_FocusPrev,
        ImGuiNavInput_FocusNext = C.ImGuiNavInput_FocusNext,
        ImGuiNavInput_TweakSlow = C.ImGuiNavInput_TweakSlow,
        ImGuiNavInput_TweakFast = C.ImGuiNavInput_TweakFast,
        ImGuiNavInput_KeyMenu_ = C.ImGuiNavInput_KeyMenu_,
        ImGuiNavInput_KeyLeft_ = C.ImGuiNavInput_KeyLeft_,
        ImGuiNavInput_KeyRight_ = C.ImGuiNavInput_KeyRight_,
        ImGuiNavInput_KeyUp_ = C.ImGuiNavInput_KeyUp_,
        ImGuiNavInput_KeyDown_ = C.ImGuiNavInput_KeyDown_,
        ImGuiNavInput_COUNT = C.ImGuiNavInput_COUNT,
        ImGuiNavInput_InternalStart_ = C.ImGuiNavInput_InternalStart_,
    },
    ImGuiConfigFlags_ = {
        ImGuiConfigFlags_None = C.ImGuiConfigFlags_None,
        ImGuiConfigFlags_NavEnableKeyboard = C.ImGuiConfigFlags_NavEnableKeyboard,
        ImGuiConfigFlags_NavEnableGamepad = C.ImGuiConfigFlags_NavEnableGamepad,
        ImGuiConfigFlags_NavEnableSetMousePos = C.ImGuiConfigFlags_NavEnableSetMousePos,
        ImGuiConfigFlags_NavNoCaptureKeyboard = C.ImGuiConfigFlags_NavNoCaptureKeyboard,
        ImGuiConfigFlags_NoMouse = C.ImGuiConfigFlags_NoMouse,
        ImGuiConfigFlags_NoMouseCursorChange = C.ImGuiConfigFlags_NoMouseCursorChange,
        ImGuiConfigFlags_IsSRGB = C.ImGuiConfigFlags_IsSRGB,
        ImGuiConfigFlags_IsTouchScreen = C.ImGuiConfigFlags_IsTouchScreen,
    },
    ImGuiBackendFlags_ = {
        ImGuiBackendFlags_None = C.ImGuiBackendFlags_None,
        ImGuiBackendFlags_HasGamepad = C.ImGuiBackendFlags_HasGamepad,
        ImGuiBackendFlags_HasMouseCursors = C.ImGuiBackendFlags_HasMouseCursors,
        ImGuiBackendFlags_HasSetMousePos = C.ImGuiBackendFlags_HasSetMousePos,
        ImGuiBackendFlags_RendererHasVtxOffset = C.ImGuiBackendFlags_RendererHasVtxOffset,
    },
    ImGuiCol_ = {
        ImGuiCol_Text = C.ImGuiCol_Text,
        ImGuiCol_TextDisabled = C.ImGuiCol_TextDisabled,
        ImGuiCol_WindowBg = C.ImGuiCol_WindowBg,
        ImGuiCol_ChildBg = C.ImGuiCol_ChildBg,
        ImGuiCol_PopupBg = C.ImGuiCol_PopupBg,
        ImGuiCol_Border = C.ImGuiCol_Border,
        ImGuiCol_BorderShadow = C.ImGuiCol_BorderShadow,
        ImGuiCol_FrameBg = C.ImGuiCol_FrameBg,
        ImGuiCol_FrameBgHovered = C.ImGuiCol_FrameBgHovered,
        ImGuiCol_FrameBgActive = C.ImGuiCol_FrameBgActive,
        ImGuiCol_TitleBg = C.ImGuiCol_TitleBg,
        ImGuiCol_TitleBgActive = C.ImGuiCol_TitleBgActive,
        ImGuiCol_TitleBgCollapsed = C.ImGuiCol_TitleBgCollapsed,
        ImGuiCol_MenuBarBg = C.ImGuiCol_MenuBarBg,
        ImGuiCol_ScrollbarBg = C.ImGuiCol_ScrollbarBg,
        ImGuiCol_ScrollbarGrab = C.ImGuiCol_ScrollbarGrab,
        ImGuiCol_ScrollbarGrabHovered = C.ImGuiCol_ScrollbarGrabHovered,
        ImGuiCol_ScrollbarGrabActive = C.ImGuiCol_ScrollbarGrabActive,
        ImGuiCol_CheckMark = C.ImGuiCol_CheckMark,
        ImGuiCol_SliderGrab = C.ImGuiCol_SliderGrab,
        ImGuiCol_SliderGrabActive = C.ImGuiCol_SliderGrabActive,
        ImGuiCol_Button = C.ImGuiCol_Button,
        ImGuiCol_ButtonHovered = C.ImGuiCol_ButtonHovered,
        ImGuiCol_ButtonActive = C.ImGuiCol_ButtonActive,
        ImGuiCol_Header = C.ImGuiCol_Header,
        ImGuiCol_HeaderHovered = C.ImGuiCol_HeaderHovered,
        ImGuiCol_HeaderActive = C.ImGuiCol_HeaderActive,
        ImGuiCol_Separator = C.ImGuiCol_Separator,
        ImGuiCol_SeparatorHovered = C.ImGuiCol_SeparatorHovered,
        ImGuiCol_SeparatorActive = C.ImGuiCol_SeparatorActive,
        ImGuiCol_ResizeGrip = C.ImGuiCol_ResizeGrip,
        ImGuiCol_ResizeGripHovered = C.ImGuiCol_ResizeGripHovered,
        ImGuiCol_ResizeGripActive = C.ImGuiCol_ResizeGripActive,
        ImGuiCol_Tab = C.ImGuiCol_Tab,
        ImGuiCol_TabHovered = C.ImGuiCol_TabHovered,
        ImGuiCol_TabActive = C.ImGuiCol_TabActive,
        ImGuiCol_TabUnfocused = C.ImGuiCol_TabUnfocused,
        ImGuiCol_TabUnfocusedActive = C.ImGuiCol_TabUnfocusedActive,
        ImGuiCol_PlotLines = C.ImGuiCol_PlotLines,
        ImGuiCol_PlotLinesHovered = C.ImGuiCol_PlotLinesHovered,
        ImGuiCol_PlotHistogram = C.ImGuiCol_PlotHistogram,
        ImGuiCol_PlotHistogramHovered = C.ImGuiCol_PlotHistogramHovered,
        ImGuiCol_TableHeaderBg = C.ImGuiCol_TableHeaderBg,
        ImGuiCol_TableBorderStrong = C.ImGuiCol_TableBorderStrong,
        ImGuiCol_TableBorderLight = C.ImGuiCol_TableBorderLight,
        ImGuiCol_TableRowBg = C.ImGuiCol_TableRowBg,
        ImGuiCol_TableRowBgAlt = C.ImGuiCol_TableRowBgAlt,
        ImGuiCol_TextSelectedBg = C.ImGuiCol_TextSelectedBg,
        ImGuiCol_DragDropTarget = C.ImGuiCol_DragDropTarget,
        ImGuiCol_NavHighlight = C.ImGuiCol_NavHighlight,
        ImGuiCol_NavWindowingHighlight = C.ImGuiCol_NavWindowingHighlight,
        ImGuiCol_NavWindowingDimBg = C.ImGuiCol_NavWindowingDimBg,
        ImGuiCol_ModalWindowDimBg = C.ImGuiCol_ModalWindowDimBg,
        ImGuiCol_COUNT = C.ImGuiCol_COUNT,
    },
    ImGuiStyleVar_ = {
        ImGuiStyleVar_Alpha = C.ImGuiStyleVar_Alpha,
        ImGuiStyleVar_WindowPadding = C.ImGuiStyleVar_WindowPadding,
        ImGuiStyleVar_WindowRounding = C.ImGuiStyleVar_WindowRounding,
        ImGuiStyleVar_WindowBorderSize = C.ImGuiStyleVar_WindowBorderSize,
        ImGuiStyleVar_WindowMinSize = C.ImGuiStyleVar_WindowMinSize,
        ImGuiStyleVar_WindowTitleAlign = C.ImGuiStyleVar_WindowTitleAlign,
        ImGuiStyleVar_ChildRounding = C.ImGuiStyleVar_ChildRounding,
        ImGuiStyleVar_ChildBorderSize = C.ImGuiStyleVar_ChildBorderSize,
        ImGuiStyleVar_PopupRounding = C.ImGuiStyleVar_PopupRounding,
        ImGuiStyleVar_PopupBorderSize = C.ImGuiStyleVar_PopupBorderSize,
        ImGuiStyleVar_FramePadding = C.ImGuiStyleVar_FramePadding,
        ImGuiStyleVar_FrameRounding = C.ImGuiStyleVar_FrameRounding,
        ImGuiStyleVar_FrameBorderSize = C.ImGuiStyleVar_FrameBorderSize,
        ImGuiStyleVar_ItemSpacing = C.ImGuiStyleVar_ItemSpacing,
        ImGuiStyleVar_ItemInnerSpacing = C.ImGuiStyleVar_ItemInnerSpacing,
        ImGuiStyleVar_IndentSpacing = C.ImGuiStyleVar_IndentSpacing,
        ImGuiStyleVar_CellPadding = C.ImGuiStyleVar_CellPadding,
        ImGuiStyleVar_ScrollbarSize = C.ImGuiStyleVar_ScrollbarSize,
        ImGuiStyleVar_ScrollbarRounding = C.ImGuiStyleVar_ScrollbarRounding,
        ImGuiStyleVar_GrabMinSize = C.ImGuiStyleVar_GrabMinSize,
        ImGuiStyleVar_GrabRounding = C.ImGuiStyleVar_GrabRounding,
        ImGuiStyleVar_TabRounding = C.ImGuiStyleVar_TabRounding,
        ImGuiStyleVar_ButtonTextAlign = C.ImGuiStyleVar_ButtonTextAlign,
        ImGuiStyleVar_SelectableTextAlign = C.ImGuiStyleVar_SelectableTextAlign,
        ImGuiStyleVar_COUNT = C.ImGuiStyleVar_COUNT,
    },
    ImGuiButtonFlags_ = {
        ImGuiButtonFlags_None = C.ImGuiButtonFlags_None,
        ImGuiButtonFlags_MouseButtonLeft = C.ImGuiButtonFlags_MouseButtonLeft,
        ImGuiButtonFlags_MouseButtonRight = C.ImGuiButtonFlags_MouseButtonRight,
        ImGuiButtonFlags_MouseButtonMiddle = C.ImGuiButtonFlags_MouseButtonMiddle,
        ImGuiButtonFlags_MouseButtonMask_ = C.ImGuiButtonFlags_MouseButtonMask_,
        ImGuiButtonFlags_MouseButtonDefault_ = C.ImGuiButtonFlags_MouseButtonDefault_,
    },
    ImGuiColorEditFlags_ = {
        ImGuiColorEditFlags_None = C.ImGuiColorEditFlags_None,
        ImGuiColorEditFlags_NoAlpha = C.ImGuiColorEditFlags_NoAlpha,
        ImGuiColorEditFlags_NoPicker = C.ImGuiColorEditFlags_NoPicker,
        ImGuiColorEditFlags_NoOptions = C.ImGuiColorEditFlags_NoOptions,
        ImGuiColorEditFlags_NoSmallPreview = C.ImGuiColorEditFlags_NoSmallPreview,
        ImGuiColorEditFlags_NoInputs = C.ImGuiColorEditFlags_NoInputs,
        ImGuiColorEditFlags_NoTooltip = C.ImGuiColorEditFlags_NoTooltip,
        ImGuiColorEditFlags_NoLabel = C.ImGuiColorEditFlags_NoLabel,
        ImGuiColorEditFlags_NoSidePreview = C.ImGuiColorEditFlags_NoSidePreview,
        ImGuiColorEditFlags_NoDragDrop = C.ImGuiColorEditFlags_NoDragDrop,
        ImGuiColorEditFlags_NoBorder = C.ImGuiColorEditFlags_NoBorder,
        ImGuiColorEditFlags_AlphaBar = C.ImGuiColorEditFlags_AlphaBar,
        ImGuiColorEditFlags_AlphaPreview = C.ImGuiColorEditFlags_AlphaPreview,
        ImGuiColorEditFlags_AlphaPreviewHalf = C.ImGuiColorEditFlags_AlphaPreviewHalf,
        ImGuiColorEditFlags_HDR = C.ImGuiColorEditFlags_HDR,
        ImGuiColorEditFlags_DisplayRGB = C.ImGuiColorEditFlags_DisplayRGB,
        ImGuiColorEditFlags_DisplayHSV = C.ImGuiColorEditFlags_DisplayHSV,
        ImGuiColorEditFlags_DisplayHex = C.ImGuiColorEditFlags_DisplayHex,
        ImGuiColorEditFlags_Uint8 = C.ImGuiColorEditFlags_Uint8,
        ImGuiColorEditFlags_Float = C.ImGuiColorEditFlags_Float,
        ImGuiColorEditFlags_PickerHueBar = C.ImGuiColorEditFlags_PickerHueBar,
        ImGuiColorEditFlags_PickerHueWheel = C.ImGuiColorEditFlags_PickerHueWheel,
        ImGuiColorEditFlags_InputRGB = C.ImGuiColorEditFlags_InputRGB,
        ImGuiColorEditFlags_InputHSV = C.ImGuiColorEditFlags_InputHSV,
        ImGuiColorEditFlags__OptionsDefault = C.ImGuiColorEditFlags__OptionsDefault,
        ImGuiColorEditFlags__DisplayMask = C.ImGuiColorEditFlags__DisplayMask,
        ImGuiColorEditFlags__DataTypeMask = C.ImGuiColorEditFlags__DataTypeMask,
        ImGuiColorEditFlags__PickerMask = C.ImGuiColorEditFlags__PickerMask,
        ImGuiColorEditFlags__InputMask = C.ImGuiColorEditFlags__InputMask,
        ImGuiColorEditFlags_RGB = C.ImGuiColorEditFlags_RGB,
        ImGuiColorEditFlags_HSV = C.ImGuiColorEditFlags_HSV,
        ImGuiColorEditFlags_HEX = C.ImGuiColorEditFlags_HEX,
    },
    ImGuiSliderFlags_ = {
        ImGuiSliderFlags_None = C.ImGuiSliderFlags_None,
        ImGuiSliderFlags_AlwaysClamp = C.ImGuiSliderFlags_AlwaysClamp,
        ImGuiSliderFlags_Logarithmic = C.ImGuiSliderFlags_Logarithmic,
        ImGuiSliderFlags_NoRoundToFormat = C.ImGuiSliderFlags_NoRoundToFormat,
        ImGuiSliderFlags_NoInput = C.ImGuiSliderFlags_NoInput,
        ImGuiSliderFlags_InvalidMask_ = C.ImGuiSliderFlags_InvalidMask_,
        ImGuiSliderFlags_ClampOnInput = C.ImGuiSliderFlags_ClampOnInput,
    },
    ImGuiMouseButton_ = {
        ImGuiMouseButton_Left = C.ImGuiMouseButton_Left,
        ImGuiMouseButton_Right = C.ImGuiMouseButton_Right,
        ImGuiMouseButton_Middle = C.ImGuiMouseButton_Middle,
        ImGuiMouseButton_COUNT = C.ImGuiMouseButton_COUNT,
    },
    ImGuiMouseCursor_ = {
        ImGuiMouseCursor_None = C.ImGuiMouseCursor_None,
        ImGuiMouseCursor_Arrow = C.ImGuiMouseCursor_Arrow,
        ImGuiMouseCursor_TextInput = C.ImGuiMouseCursor_TextInput,
        ImGuiMouseCursor_ResizeAll = C.ImGuiMouseCursor_ResizeAll,
        ImGuiMouseCursor_ResizeNS = C.ImGuiMouseCursor_ResizeNS,
        ImGuiMouseCursor_ResizeEW = C.ImGuiMouseCursor_ResizeEW,
        ImGuiMouseCursor_ResizeNESW = C.ImGuiMouseCursor_ResizeNESW,
        ImGuiMouseCursor_ResizeNWSE = C.ImGuiMouseCursor_ResizeNWSE,
        ImGuiMouseCursor_Hand = C.ImGuiMouseCursor_Hand,
        ImGuiMouseCursor_NotAllowed = C.ImGuiMouseCursor_NotAllowed,
        ImGuiMouseCursor_COUNT = C.ImGuiMouseCursor_COUNT,
    },
    ImGuiCond_ = {
        ImGuiCond_None = C.ImGuiCond_None,
        ImGuiCond_Always = C.ImGuiCond_Always,
        ImGuiCond_Once = C.ImGuiCond_Once,
        ImGuiCond_FirstUseEver = C.ImGuiCond_FirstUseEver,
        ImGuiCond_Appearing = C.ImGuiCond_Appearing,
    },
    ImDrawFlags_ = {
        ImDrawFlags_None = C.ImDrawFlags_None,
        ImDrawFlags_Closed = C.ImDrawFlags_Closed,
        ImDrawFlags_RoundCornersTopLeft = C.ImDrawFlags_RoundCornersTopLeft,
        ImDrawFlags_RoundCornersTopRight = C.ImDrawFlags_RoundCornersTopRight,
        ImDrawFlags_RoundCornersBottomLeft = C.ImDrawFlags_RoundCornersBottomLeft,
        ImDrawFlags_RoundCornersBottomRight = C.ImDrawFlags_RoundCornersBottomRight,
        ImDrawFlags_RoundCornersNone = C.ImDrawFlags_RoundCornersNone,
        ImDrawFlags_RoundCornersTop = C.ImDrawFlags_RoundCornersTop,
        ImDrawFlags_RoundCornersBottom = C.ImDrawFlags_RoundCornersBottom,
        ImDrawFlags_RoundCornersLeft = C.ImDrawFlags_RoundCornersLeft,
        ImDrawFlags_RoundCornersRight = C.ImDrawFlags_RoundCornersRight,
        ImDrawFlags_RoundCornersAll = C.ImDrawFlags_RoundCornersAll,
        ImDrawFlags_RoundCornersDefault_ = C.ImDrawFlags_RoundCornersDefault_,
        ImDrawFlags_RoundCornersMask_ = C.ImDrawFlags_RoundCornersMask_,
    },
    ImDrawListFlags_ = {
        ImDrawListFlags_None = C.ImDrawListFlags_None,
        ImDrawListFlags_AntiAliasedLines = C.ImDrawListFlags_AntiAliasedLines,
        ImDrawListFlags_AntiAliasedLinesUseTex = C.ImDrawListFlags_AntiAliasedLinesUseTex,
        ImDrawListFlags_AntiAliasedFill = C.ImDrawListFlags_AntiAliasedFill,
        ImDrawListFlags_AllowVtxOffset = C.ImDrawListFlags_AllowVtxOffset,
    },
    ImFontAtlasFlags_ = {
        ImFontAtlasFlags_None = C.ImFontAtlasFlags_None,
        ImFontAtlasFlags_NoPowerOfTwoHeight = C.ImFontAtlasFlags_NoPowerOfTwoHeight,
        ImFontAtlasFlags_NoMouseCursors = C.ImFontAtlasFlags_NoMouseCursors,
        ImFontAtlasFlags_NoBakedLines = C.ImFontAtlasFlags_NoBakedLines,
    },
    ImGuiViewportFlags_ = {
        ImGuiViewportFlags_None = C.ImGuiViewportFlags_None,
        ImGuiViewportFlags_IsPlatformWindow = C.ImGuiViewportFlags_IsPlatformWindow,
        ImGuiViewportFlags_IsPlatformMonitor = C.ImGuiViewportFlags_IsPlatformMonitor,
        ImGuiViewportFlags_OwnedByApp = C.ImGuiViewportFlags_OwnedByApp,
    },
    ImDrawCornerFlags_ = {
        ImDrawCornerFlags_None = C.ImDrawCornerFlags_None,
        ImDrawCornerFlags_TopLeft = C.ImDrawCornerFlags_TopLeft,
        ImDrawCornerFlags_TopRight = C.ImDrawCornerFlags_TopRight,
        ImDrawCornerFlags_BotLeft = C.ImDrawCornerFlags_BotLeft,
        ImDrawCornerFlags_BotRight = C.ImDrawCornerFlags_BotRight,
        ImDrawCornerFlags_All = C.ImDrawCornerFlags_All,
        ImDrawCornerFlags_Top = C.ImDrawCornerFlags_Top,
        ImDrawCornerFlags_Bot = C.ImDrawCornerFlags_Bot,
        ImDrawCornerFlags_Left = C.ImDrawCornerFlags_Left,
        ImDrawCornerFlags_Right = C.ImDrawCornerFlags_Right,
    },
}
---@class GLADapiproc
---@class GLADloadfunc
---@class GLADuserptrloadfunc
---@class GLFWwindow
---@class GLFWmonitor
---@class size_t
---@class ImDrawListSharedData
---@class ImFontBuilderIO
---@class ImGuiContext
---@class ImGuiCol
---@class ImGuiCond
---@class ImGuiDataType
---@class ImGuiDir
---@class ImGuiKey
---@class ImGuiMouseButton
---@class ImGuiMouseCursor
---@class ImGuiSortDirection
---@class ImGuiStyleVar
---@class ImGuiTableBgTarget
---@class ImDrawListFlags
---@class ImFontAtlasFlags
---@class ImGuiBackendFlags
---@class ImGuiButtonFlags
---@class ImGuiColorEditFlags
---@class ImGuiConfigFlags
---@class ImGuiComboFlags
---@class ImGuiDragDropFlags
---@class ImGuiFocusedFlags
---@class ImGuiHoveredFlags
---@class ImGuiInputTextFlags
---@class ImGuiKeyModFlags
---@class ImGuiPopupFlags
---@class ImGuiSelectableFlags
---@class ImGuiSliderFlags
---@class ImGuiTabBarFlags
---@class ImGuiTabItemFlags
---@class ImGuiTableFlags
---@class ImGuiTableColumnFlags
---@class ImGuiTableRowFlags
---@class ImGuiTreeNodeFlags
---@class ImGuiViewportFlags
---@class ImGuiWindowFlags
---@class ImTextureID
---@class ImGuiID
---@class ImGuiInputTextCallback
---@class ImGuiSizeCallback
---@class ImGuiMemAllocFunc
---@class ImGuiMemFreeFunc
---@class ImWchar16
---@class ImWchar
---@class ImU8
---@class ImS16
---@class ImU32
---@class ImVec2
---@class ImVec4
---@class ImGuiStyle
---@class ImGuiIO
---@class ImGuiInputTextCallbackData
---@class ImGuiSizeCallbackData
---@class ImGuiPayload
---@class ImGuiTableColumnSortSpecs
---@class ImGuiTableSortSpecs
---@class ImGuiStorage
---@class ImGuiStoragePair
---@class ImDrawCallback
---@class ImDrawCmd
---@class ImDrawIdx
---@class ImDrawVert
---@class ImDrawCmdHeader
---@class ImDrawChannel
---@class ImDrawListSplitter
---@class ImDrawList
---@class ImDrawData
---@class ImFontConfig
---@class ImFontGlyph
---@class ImFontAtlasCustomRect
---@class ImFontAtlas
---@class ImFont
---@class ImGuiViewport
---@class va_list
-----------------------------------------------------------------------------
-- imgui.dll
-----------------------------------------------------------------------------
---@type Table<string, any>
local imgui = ffi.load('imgui')
M.cache.imgui = imgui
M.libs.imgui = {
    ---@type fun(glsl_version:string):bool
    ImGui_ImplOpenGL3_Init = imgui.ImGui_ImplOpenGL3_Init,
    ---@type fun():nil
    ImGui_ImplOpenGL3_Shutdown = imgui.ImGui_ImplOpenGL3_Shutdown,
    ---@type fun():nil
    ImGui_ImplOpenGL3_NewFrame = imgui.ImGui_ImplOpenGL3_NewFrame,
    ---@type fun(draw_data:any):nil
    ImGui_ImplOpenGL3_RenderDrawData = imgui.ImGui_ImplOpenGL3_RenderDrawData,
    ---@type fun():bool
    ImGui_ImplOpenGL3_CreateFontsTexture = imgui.ImGui_ImplOpenGL3_CreateFontsTexture,
    ---@type fun():nil
    ImGui_ImplOpenGL3_DestroyFontsTexture = imgui.ImGui_ImplOpenGL3_DestroyFontsTexture,
    ---@type fun():bool
    ImGui_ImplOpenGL3_CreateDeviceObjects = imgui.ImGui_ImplOpenGL3_CreateDeviceObjects,
    ---@type fun():nil
    ImGui_ImplOpenGL3_DestroyDeviceObjects = imgui.ImGui_ImplOpenGL3_DestroyDeviceObjects,
    ---@type fun(window:any, install_callbacks:bool):bool
    ImGui_ImplGlfw_InitForOpenGL = imgui.ImGui_ImplGlfw_InitForOpenGL,
    ---@type fun(window:any, install_callbacks:bool):bool
    ImGui_ImplGlfw_InitForVulkan = imgui.ImGui_ImplGlfw_InitForVulkan,
    ---@type fun(window:any, install_callbacks:bool):bool
    ImGui_ImplGlfw_InitForOther = imgui.ImGui_ImplGlfw_InitForOther,
    ---@type fun():nil
    ImGui_ImplGlfw_Shutdown = imgui.ImGui_ImplGlfw_Shutdown,
    ---@type fun():nil
    ImGui_ImplGlfw_NewFrame = imgui.ImGui_ImplGlfw_NewFrame,
    ---@type fun(window:any, button:integer, action:integer, mods:integer):nil
    ImGui_ImplGlfw_MouseButtonCallback = imgui.ImGui_ImplGlfw_MouseButtonCallback,
    ---@type fun(window:any, xoffset:number, yoffset:number):nil
    ImGui_ImplGlfw_ScrollCallback = imgui.ImGui_ImplGlfw_ScrollCallback,
    ---@type fun(window:any, key:integer, scancode:integer, action:integer, mods:integer):nil
    ImGui_ImplGlfw_KeyCallback = imgui.ImGui_ImplGlfw_KeyCallback,
    ---@type fun(window:any, c:integer):nil
    ImGui_ImplGlfw_CharCallback = imgui.ImGui_ImplGlfw_CharCallback,
    ---@type fun(monitor:any, event:integer):nil
    ImGui_ImplGlfw_MonitorCallback = imgui.ImGui_ImplGlfw_MonitorCallback,
    ---@type fun(shared_font_atlas:any):any
    CreateContext = imgui.CreateContext,
    ---@type fun(ctx:any):nil
    DestroyContext = imgui.DestroyContext,
    ---@type fun():any
    GetCurrentContext = imgui.GetCurrentContext,
    ---@type fun(ctx:any):nil
    SetCurrentContext = imgui.SetCurrentContext,
    ---@type fun():any
    GetIO = imgui.GetIO,
    ---@type fun():any
    GetStyle = imgui.GetStyle,
    ---@type fun():nil
    NewFrame = imgui.NewFrame,
    ---@type fun():nil
    EndFrame = imgui.EndFrame,
    ---@type fun():nil
    Render = imgui.Render,
    ---@type fun():any
    GetDrawData = imgui.GetDrawData,
    ---@type fun(p_open:any):nil
    ShowDemoWindow = imgui.ShowDemoWindow,
    ---@type fun(p_open:any):nil
    ShowMetricsWindow = imgui.ShowMetricsWindow,
    ---@type fun(p_open:any):nil
    ShowAboutWindow = imgui.ShowAboutWindow,
    ---@type fun(ref:any):nil
    ShowStyleEditor = imgui.ShowStyleEditor,
    ---@type fun(label:string):bool
    ShowStyleSelector = imgui.ShowStyleSelector,
    ---@type fun(label:string):nil
    ShowFontSelector = imgui.ShowFontSelector,
    ---@type fun():nil
    ShowUserGuide = imgui.ShowUserGuide,
    ---@type fun():string
    GetVersion = imgui.GetVersion,
    ---@type fun(dst:any):nil
    StyleColorsDark = imgui.StyleColorsDark,
    ---@type fun(dst:any):nil
    StyleColorsLight = imgui.StyleColorsLight,
    ---@type fun(dst:any):nil
    StyleColorsClassic = imgui.StyleColorsClassic,
    ---@type fun(name:string, p_open:any, flags:ImGuiWindowFlags):bool
    Begin = imgui.Begin,
    ---@type fun():nil
    End = imgui.End,
    ---@type fun(str_id:string, size:any, border:bool, flags:ImGuiWindowFlags):bool
    BeginChild = imgui.BeginChild,
    ---@type fun(id:ImGuiID, size:any, border:bool, flags:ImGuiWindowFlags):bool
    BeginChild = imgui.BeginChild,
    ---@type fun():nil
    EndChild = imgui.EndChild,
    ---@type fun():bool
    IsWindowAppearing = imgui.IsWindowAppearing,
    ---@type fun():bool
    IsWindowCollapsed = imgui.IsWindowCollapsed,
    ---@type fun(flags:ImGuiFocusedFlags):bool
    IsWindowFocused = imgui.IsWindowFocused,
    ---@type fun(flags:ImGuiHoveredFlags):bool
    IsWindowHovered = imgui.IsWindowHovered,
    ---@type fun():any
    GetWindowDrawList = imgui.GetWindowDrawList,
    ---@type fun():ImVec2
    GetWindowPos = imgui.GetWindowPos,
    ---@type fun():ImVec2
    GetWindowSize = imgui.GetWindowSize,
    ---@type fun():float
    GetWindowWidth = imgui.GetWindowWidth,
    ---@type fun():float
    GetWindowHeight = imgui.GetWindowHeight,
    ---@type fun(pos:any, cond:ImGuiCond, pivot:any):nil
    SetNextWindowPos = imgui.SetNextWindowPos,
    ---@type fun(size:any, cond:ImGuiCond):nil
    SetNextWindowSize = imgui.SetNextWindowSize,
    ---@type fun(size_min:any, size_max:any, custom_callback:ImGuiSizeCallback, custom_callback_data:any):nil
    SetNextWindowSizeConstraints = imgui.SetNextWindowSizeConstraints,
    ---@type fun(size:any):nil
    SetNextWindowContentSize = imgui.SetNextWindowContentSize,
    ---@type fun(collapsed:bool, cond:ImGuiCond):nil
    SetNextWindowCollapsed = imgui.SetNextWindowCollapsed,
    ---@type fun():nil
    SetNextWindowFocus = imgui.SetNextWindowFocus,
    ---@type fun(alpha:float):nil
    SetNextWindowBgAlpha = imgui.SetNextWindowBgAlpha,
    ---@type fun(pos:any, cond:ImGuiCond):nil
    SetWindowPos = imgui.SetWindowPos,
    ---@type fun(size:any, cond:ImGuiCond):nil
    SetWindowSize = imgui.SetWindowSize,
    ---@type fun(collapsed:bool, cond:ImGuiCond):nil
    SetWindowCollapsed = imgui.SetWindowCollapsed,
    ---@type fun():nil
    SetWindowFocus = imgui.SetWindowFocus,
    ---@type fun(scale:float):nil
    SetWindowFontScale = imgui.SetWindowFontScale,
    ---@type fun(name:string, pos:any, cond:ImGuiCond):nil
    SetWindowPos = imgui.SetWindowPos,
    ---@type fun(name:string, size:any, cond:ImGuiCond):nil
    SetWindowSize = imgui.SetWindowSize,
    ---@type fun(name:string, collapsed:bool, cond:ImGuiCond):nil
    SetWindowCollapsed = imgui.SetWindowCollapsed,
    ---@type fun(name:string):nil
    SetWindowFocus = imgui.SetWindowFocus,
    ---@type fun():ImVec2
    GetContentRegionAvail = imgui.GetContentRegionAvail,
    ---@type fun():ImVec2
    GetContentRegionMax = imgui.GetContentRegionMax,
    ---@type fun():ImVec2
    GetWindowContentRegionMin = imgui.GetWindowContentRegionMin,
    ---@type fun():ImVec2
    GetWindowContentRegionMax = imgui.GetWindowContentRegionMax,
    ---@type fun():float
    GetWindowContentRegionWidth = imgui.GetWindowContentRegionWidth,
    ---@type fun():float
    GetScrollX = imgui.GetScrollX,
    ---@type fun():float
    GetScrollY = imgui.GetScrollY,
    ---@type fun(scroll_x:float):nil
    SetScrollX = imgui.SetScrollX,
    ---@type fun(scroll_y:float):nil
    SetScrollY = imgui.SetScrollY,
    ---@type fun():float
    GetScrollMaxX = imgui.GetScrollMaxX,
    ---@type fun():float
    GetScrollMaxY = imgui.GetScrollMaxY,
    ---@type fun(center_x_ratio:float):nil
    SetScrollHereX = imgui.SetScrollHereX,
    ---@type fun(center_y_ratio:float):nil
    SetScrollHereY = imgui.SetScrollHereY,
    ---@type fun(local_x:float, center_x_ratio:float):nil
    SetScrollFromPosX = imgui.SetScrollFromPosX,
    ---@type fun(local_y:float, center_y_ratio:float):nil
    SetScrollFromPosY = imgui.SetScrollFromPosY,
    ---@type fun(font:any):nil
    PushFont = imgui.PushFont,
    ---@type fun():nil
    PopFont = imgui.PopFont,
    ---@type fun(idx:ImGuiCol, col:ImU32):nil
    PushStyleColor = imgui.PushStyleColor,
    ---@type fun(idx:ImGuiCol, col:any):nil
    PushStyleColor = imgui.PushStyleColor,
    ---@type fun(count:integer):nil
    PopStyleColor = imgui.PopStyleColor,
    ---@type fun(idx:ImGuiStyleVar, val:float):nil
    PushStyleVar = imgui.PushStyleVar,
    ---@type fun(idx:ImGuiStyleVar, val:any):nil
    PushStyleVar = imgui.PushStyleVar,
    ---@type fun(count:integer):nil
    PopStyleVar = imgui.PopStyleVar,
    ---@type fun(allow_keyboard_focus:bool):nil
    PushAllowKeyboardFocus = imgui.PushAllowKeyboardFocus,
    ---@type fun():nil
    PopAllowKeyboardFocus = imgui.PopAllowKeyboardFocus,
    ---@type fun(repeat:bool):nil
    PushButtonRepeat = imgui.PushButtonRepeat,
    ---@type fun():nil
    PopButtonRepeat = imgui.PopButtonRepeat,
    ---@type fun(item_width:float):nil
    PushItemWidth = imgui.PushItemWidth,
    ---@type fun():nil
    PopItemWidth = imgui.PopItemWidth,
    ---@type fun(item_width:float):nil
    SetNextItemWidth = imgui.SetNextItemWidth,
    ---@type fun():float
    CalcItemWidth = imgui.CalcItemWidth,
    ---@type fun(wrap_local_pos_x:float):nil
    PushTextWrapPos = imgui.PushTextWrapPos,
    ---@type fun():nil
    PopTextWrapPos = imgui.PopTextWrapPos,
    ---@type fun():any
    GetFont = imgui.GetFont,
    ---@type fun():float
    GetFontSize = imgui.GetFontSize,
    ---@type fun():ImVec2
    GetFontTexUvWhitePixel = imgui.GetFontTexUvWhitePixel,
    ---@type fun(idx:ImGuiCol, alpha_mul:float):ImU32
    GetColorU32 = imgui.GetColorU32,
    ---@type fun(col:any):ImU32
    GetColorU32 = imgui.GetColorU32,
    ---@type fun(col:ImU32):ImU32
    GetColorU32 = imgui.GetColorU32,
    ---@type fun(idx:ImGuiCol):any
    GetStyleColorVec4 = imgui.GetStyleColorVec4,
    ---@type fun():nil
    Separator = imgui.Separator,
    ---@type fun(offset_from_start_x:float, spacing:float):nil
    SameLine = imgui.SameLine,
    ---@type fun():nil
    NewLine = imgui.NewLine,
    ---@type fun():nil
    Spacing = imgui.Spacing,
    ---@type fun(size:any):nil
    Dummy = imgui.Dummy,
    ---@type fun(indent_w:float):nil
    Indent = imgui.Indent,
    ---@type fun(indent_w:float):nil
    Unindent = imgui.Unindent,
    ---@type fun():nil
    BeginGroup = imgui.BeginGroup,
    ---@type fun():nil
    EndGroup = imgui.EndGroup,
    ---@type fun():ImVec2
    GetCursorPos = imgui.GetCursorPos,
    ---@type fun():float
    GetCursorPosX = imgui.GetCursorPosX,
    ---@type fun():float
    GetCursorPosY = imgui.GetCursorPosY,
    ---@type fun(local_pos:any):nil
    SetCursorPos = imgui.SetCursorPos,
    ---@type fun(local_x:float):nil
    SetCursorPosX = imgui.SetCursorPosX,
    ---@type fun(local_y:float):nil
    SetCursorPosY = imgui.SetCursorPosY,
    ---@type fun():ImVec2
    GetCursorStartPos = imgui.GetCursorStartPos,
    ---@type fun():ImVec2
    GetCursorScreenPos = imgui.GetCursorScreenPos,
    ---@type fun(pos:any):nil
    SetCursorScreenPos = imgui.SetCursorScreenPos,
    ---@type fun():nil
    AlignTextToFramePadding = imgui.AlignTextToFramePadding,
    ---@type fun():float
    GetTextLineHeight = imgui.GetTextLineHeight,
    ---@type fun():float
    GetTextLineHeightWithSpacing = imgui.GetTextLineHeightWithSpacing,
    ---@type fun():float
    GetFrameHeight = imgui.GetFrameHeight,
    ---@type fun():float
    GetFrameHeightWithSpacing = imgui.GetFrameHeightWithSpacing,
    ---@type fun(str_id:string):nil
    PushID = imgui.PushID,
    ---@type fun(str_id_begin:string, str_id_end:string):nil
    PushID = imgui.PushID,
    ---@type fun(ptr_id:any):nil
    PushID = imgui.PushID,
    ---@type fun(int_id:integer):nil
    PushID = imgui.PushID,
    ---@type fun():nil
    PopID = imgui.PopID,
    ---@type fun(str_id:string):ImGuiID
    GetID = imgui.GetID,
    ---@type fun(str_id_begin:string, str_id_end:string):ImGuiID
    GetID = imgui.GetID,
    ---@type fun(ptr_id:any):ImGuiID
    GetID = imgui.GetID,
    ---@type fun(text:string, text_end:string):nil
    TextUnformatted = imgui.TextUnformatted,
    ---@type fun(fmt:string):nil
    Text = imgui.Text,
    ---@type fun(fmt:string, args:va_list):nil
    TextV = imgui.TextV,
    ---@type fun(col:any, fmt:string):nil
    TextColored = imgui.TextColored,
    ---@type fun(col:any, fmt:string, args:va_list):nil
    TextColoredV = imgui.TextColoredV,
    ---@type fun(fmt:string):nil
    TextDisabled = imgui.TextDisabled,
    ---@type fun(fmt:string, args:va_list):nil
    TextDisabledV = imgui.TextDisabledV,
    ---@type fun(fmt:string):nil
    TextWrapped = imgui.TextWrapped,
    ---@type fun(fmt:string, args:va_list):nil
    TextWrappedV = imgui.TextWrappedV,
    ---@type fun(label:string, fmt:string):nil
    LabelText = imgui.LabelText,
    ---@type fun(label:string, fmt:string, args:va_list):nil
    LabelTextV = imgui.LabelTextV,
    ---@type fun(fmt:string):nil
    BulletText = imgui.BulletText,
    ---@type fun(fmt:string, args:va_list):nil
    BulletTextV = imgui.BulletTextV,
    ---@type fun(label:string, size:any):bool
    Button = imgui.Button,
    ---@type fun(label:string):bool
    SmallButton = imgui.SmallButton,
    ---@type fun(str_id:string, size:any, flags:ImGuiButtonFlags):bool
    InvisibleButton = imgui.InvisibleButton,
    ---@type fun(str_id:string, dir:ImGuiDir):bool
    ArrowButton = imgui.ArrowButton,
    ---@type fun(user_texture_id:ImTextureID, size:any, uv0:any, uv1:any, tint_col:any, border_col:any):nil
    Image = imgui.Image,
    ---@type fun(user_texture_id:ImTextureID, size:any, uv0:any, uv1:any, frame_padding:integer, bg_col:any, tint_col:any):bool
    ImageButton = imgui.ImageButton,
    ---@type fun(label:string, v:any):bool
    Checkbox = imgui.Checkbox,
    ---@type fun(label:string, flags:any, flags_value:integer):bool
    CheckboxFlags = imgui.CheckboxFlags,
    ---@type fun(label:string, flags:any, flags_value:integer):bool
    CheckboxFlags = imgui.CheckboxFlags,
    ---@type fun(label:string, active:bool):bool
    RadioButton = imgui.RadioButton,
    ---@type fun(label:string, v:any, v_button:integer):bool
    RadioButton = imgui.RadioButton,
    ---@type fun(fraction:float, size_arg:any, overlay:string):nil
    ProgressBar = imgui.ProgressBar,
    ---@type fun():nil
    Bullet = imgui.Bullet,
    ---@type fun(label:string, preview_value:string, flags:ImGuiComboFlags):bool
    BeginCombo = imgui.BeginCombo,
    ---@type fun():nil
    EndCombo = imgui.EndCombo,
    ---@type fun(label:string, current_item:any, items:any, items_count:integer, popup_max_height_in_items:integer):bool
    Combo = imgui.Combo,
    ---@type fun(label:string, current_item:any, items_separated_by_zeros:string, popup_max_height_in_items:integer):bool
    Combo = imgui.Combo,
    ---@type fun(label:string, current_item:any, items_getter:any, data:any, items_count:integer, popup_max_height_in_items:integer):bool
    Combo = imgui.Combo,
    ---@type fun(label:string, v:any, v_speed:float, v_min:float, v_max:float, format:string, flags:ImGuiSliderFlags):bool
    DragFloat = imgui.DragFloat,
    ---@type fun(label:string, v:any, v_speed:float, v_min:float, v_max:float, format:string, flags:ImGuiSliderFlags):bool
    DragFloat2 = imgui.DragFloat2,
    ---@type fun(label:string, v:any, v_speed:float, v_min:float, v_max:float, format:string, flags:ImGuiSliderFlags):bool
    DragFloat3 = imgui.DragFloat3,
    ---@type fun(label:string, v:any, v_speed:float, v_min:float, v_max:float, format:string, flags:ImGuiSliderFlags):bool
    DragFloat4 = imgui.DragFloat4,
    ---@type fun(label:string, v_current_min:any, v_current_max:any, v_speed:float, v_min:float, v_max:float, format:string, format_max:string, flags:ImGuiSliderFlags):bool
    DragFloatRange2 = imgui.DragFloatRange2,
    ---@type fun(label:string, v:any, v_speed:float, v_min:integer, v_max:integer, format:string, flags:ImGuiSliderFlags):bool
    DragInt = imgui.DragInt,
    ---@type fun(label:string, v:any, v_speed:float, v_min:integer, v_max:integer, format:string, flags:ImGuiSliderFlags):bool
    DragInt2 = imgui.DragInt2,
    ---@type fun(label:string, v:any, v_speed:float, v_min:integer, v_max:integer, format:string, flags:ImGuiSliderFlags):bool
    DragInt3 = imgui.DragInt3,
    ---@type fun(label:string, v:any, v_speed:float, v_min:integer, v_max:integer, format:string, flags:ImGuiSliderFlags):bool
    DragInt4 = imgui.DragInt4,
    ---@type fun(label:string, v_current_min:any, v_current_max:any, v_speed:float, v_min:integer, v_max:integer, format:string, format_max:string, flags:ImGuiSliderFlags):bool
    DragIntRange2 = imgui.DragIntRange2,
    ---@type fun(label:string, data_type:ImGuiDataType, p_data:any, v_speed:float, p_min:any, p_max:any, format:string, flags:ImGuiSliderFlags):bool
    DragScalar = imgui.DragScalar,
    ---@type fun(label:string, data_type:ImGuiDataType, p_data:any, components:integer, v_speed:float, p_min:any, p_max:any, format:string, flags:ImGuiSliderFlags):bool
    DragScalarN = imgui.DragScalarN,
    ---@type fun(label:string, v:any, v_min:float, v_max:float, format:string, flags:ImGuiSliderFlags):bool
    SliderFloat = imgui.SliderFloat,
    ---@type fun(label:string, v:any, v_min:float, v_max:float, format:string, flags:ImGuiSliderFlags):bool
    SliderFloat2 = imgui.SliderFloat2,
    ---@type fun(label:string, v:any, v_min:float, v_max:float, format:string, flags:ImGuiSliderFlags):bool
    SliderFloat3 = imgui.SliderFloat3,
    ---@type fun(label:string, v:any, v_min:float, v_max:float, format:string, flags:ImGuiSliderFlags):bool
    SliderFloat4 = imgui.SliderFloat4,
    ---@type fun(label:string, v_rad:any, v_degrees_min:float, v_degrees_max:float, format:string, flags:ImGuiSliderFlags):bool
    SliderAngle = imgui.SliderAngle,
    ---@type fun(label:string, v:any, v_min:integer, v_max:integer, format:string, flags:ImGuiSliderFlags):bool
    SliderInt = imgui.SliderInt,
    ---@type fun(label:string, v:any, v_min:integer, v_max:integer, format:string, flags:ImGuiSliderFlags):bool
    SliderInt2 = imgui.SliderInt2,
    ---@type fun(label:string, v:any, v_min:integer, v_max:integer, format:string, flags:ImGuiSliderFlags):bool
    SliderInt3 = imgui.SliderInt3,
    ---@type fun(label:string, v:any, v_min:integer, v_max:integer, format:string, flags:ImGuiSliderFlags):bool
    SliderInt4 = imgui.SliderInt4,
    ---@type fun(label:string, data_type:ImGuiDataType, p_data:any, p_min:any, p_max:any, format:string, flags:ImGuiSliderFlags):bool
    SliderScalar = imgui.SliderScalar,
    ---@type fun(label:string, data_type:ImGuiDataType, p_data:any, components:integer, p_min:any, p_max:any, format:string, flags:ImGuiSliderFlags):bool
    SliderScalarN = imgui.SliderScalarN,
    ---@type fun(label:string, size:any, v:any, v_min:float, v_max:float, format:string, flags:ImGuiSliderFlags):bool
    VSliderFloat = imgui.VSliderFloat,
    ---@type fun(label:string, size:any, v:any, v_min:integer, v_max:integer, format:string, flags:ImGuiSliderFlags):bool
    VSliderInt = imgui.VSliderInt,
    ---@type fun(label:string, size:any, data_type:ImGuiDataType, p_data:any, p_min:any, p_max:any, format:string, flags:ImGuiSliderFlags):bool
    VSliderScalar = imgui.VSliderScalar,
    ---@type fun(label:string, buf:any, buf_size:size_t, flags:ImGuiInputTextFlags, callback:ImGuiInputTextCallback, user_data:any):bool
    InputText = imgui.InputText,
    ---@type fun(label:string, buf:any, buf_size:size_t, size:any, flags:ImGuiInputTextFlags, callback:ImGuiInputTextCallback, user_data:any):bool
    InputTextMultiline = imgui.InputTextMultiline,
    ---@type fun(label:string, hint:string, buf:any, buf_size:size_t, flags:ImGuiInputTextFlags, callback:ImGuiInputTextCallback, user_data:any):bool
    InputTextWithHint = imgui.InputTextWithHint,
    ---@type fun(label:string, v:any, step:float, step_fast:float, format:string, flags:ImGuiInputTextFlags):bool
    InputFloat = imgui.InputFloat,
    ---@type fun(label:string, v:any, format:string, flags:ImGuiInputTextFlags):bool
    InputFloat2 = imgui.InputFloat2,
    ---@type fun(label:string, v:any, format:string, flags:ImGuiInputTextFlags):bool
    InputFloat3 = imgui.InputFloat3,
    ---@type fun(label:string, v:any, format:string, flags:ImGuiInputTextFlags):bool
    InputFloat4 = imgui.InputFloat4,
    ---@type fun(label:string, v:any, step:integer, step_fast:integer, flags:ImGuiInputTextFlags):bool
    InputInt = imgui.InputInt,
    ---@type fun(label:string, v:any, flags:ImGuiInputTextFlags):bool
    InputInt2 = imgui.InputInt2,
    ---@type fun(label:string, v:any, flags:ImGuiInputTextFlags):bool
    InputInt3 = imgui.InputInt3,
    ---@type fun(label:string, v:any, flags:ImGuiInputTextFlags):bool
    InputInt4 = imgui.InputInt4,
    ---@type fun(label:string, v:any, step:number, step_fast:number, format:string, flags:ImGuiInputTextFlags):bool
    InputDouble = imgui.InputDouble,
    ---@type fun(label:string, data_type:ImGuiDataType, p_data:any, p_step:any, p_step_fast:any, format:string, flags:ImGuiInputTextFlags):bool
    InputScalar = imgui.InputScalar,
    ---@type fun(label:string, data_type:ImGuiDataType, p_data:any, components:integer, p_step:any, p_step_fast:any, format:string, flags:ImGuiInputTextFlags):bool
    InputScalarN = imgui.InputScalarN,
    ---@type fun(label:string, col:any, flags:ImGuiColorEditFlags):bool
    ColorEdit3 = imgui.ColorEdit3,
    ---@type fun(label:string, col:any, flags:ImGuiColorEditFlags):bool
    ColorEdit4 = imgui.ColorEdit4,
    ---@type fun(label:string, col:any, flags:ImGuiColorEditFlags):bool
    ColorPicker3 = imgui.ColorPicker3,
    ---@type fun(label:string, col:any, flags:ImGuiColorEditFlags, ref_col:any):bool
    ColorPicker4 = imgui.ColorPicker4,
    ---@type fun(desc_id:string, col:any, flags:ImGuiColorEditFlags, size:ImVec2):bool
    ColorButton = imgui.ColorButton,
    ---@type fun(flags:ImGuiColorEditFlags):nil
    SetColorEditOptions = imgui.SetColorEditOptions,
    ---@type fun(label:string):bool
    TreeNode = imgui.TreeNode,
    ---@type fun(str_id:string, fmt:string):bool
    TreeNode = imgui.TreeNode,
    ---@type fun(ptr_id:any, fmt:string):bool
    TreeNode = imgui.TreeNode,
    ---@type fun(str_id:string, fmt:string, args:va_list):bool
    TreeNodeV = imgui.TreeNodeV,
    ---@type fun(ptr_id:any, fmt:string, args:va_list):bool
    TreeNodeV = imgui.TreeNodeV,
    ---@type fun(label:string, flags:ImGuiTreeNodeFlags):bool
    TreeNodeEx = imgui.TreeNodeEx,
    ---@type fun(str_id:string, flags:ImGuiTreeNodeFlags, fmt:string):bool
    TreeNodeEx = imgui.TreeNodeEx,
    ---@type fun(ptr_id:any, flags:ImGuiTreeNodeFlags, fmt:string):bool
    TreeNodeEx = imgui.TreeNodeEx,
    ---@type fun(str_id:string, flags:ImGuiTreeNodeFlags, fmt:string, args:va_list):bool
    TreeNodeExV = imgui.TreeNodeExV,
    ---@type fun(ptr_id:any, flags:ImGuiTreeNodeFlags, fmt:string, args:va_list):bool
    TreeNodeExV = imgui.TreeNodeExV,
    ---@type fun(str_id:string):nil
    TreePush = imgui.TreePush,
    ---@type fun(ptr_id:any):nil
    TreePush = imgui.TreePush,
    ---@type fun():nil
    TreePop = imgui.TreePop,
    ---@type fun():float
    GetTreeNodeToLabelSpacing = imgui.GetTreeNodeToLabelSpacing,
    ---@type fun(label:string, flags:ImGuiTreeNodeFlags):bool
    CollapsingHeader = imgui.CollapsingHeader,
    ---@type fun(label:string, p_visible:any, flags:ImGuiTreeNodeFlags):bool
    CollapsingHeader = imgui.CollapsingHeader,
    ---@type fun(is_open:bool, cond:ImGuiCond):nil
    SetNextItemOpen = imgui.SetNextItemOpen,
    ---@type fun(label:string, selected:bool, flags:ImGuiSelectableFlags, size:any):bool
    Selectable = imgui.Selectable,
    ---@type fun(label:string, p_selected:any, flags:ImGuiSelectableFlags, size:any):bool
    Selectable = imgui.Selectable,
    ---@type fun(label:string, size:any):bool
    BeginListBox = imgui.BeginListBox,
    ---@type fun():nil
    EndListBox = imgui.EndListBox,
    ---@type fun(label:string, current_item:any, items:any, items_count:integer, height_in_items:integer):bool
    ListBox = imgui.ListBox,
    ---@type fun(label:string, current_item:any, items_getter:any, data:any, items_count:integer, height_in_items:integer):bool
    ListBox = imgui.ListBox,
    ---@type fun(label:string, values:any, values_count:integer, values_offset:integer, overlay_text:string, scale_min:float, scale_max:float, graph_size:ImVec2, stride:integer):nil
    PlotLines = imgui.PlotLines,
    ---@type fun(label:string, values_getter:any, data:any, values_count:integer, values_offset:integer, overlay_text:string, scale_min:float, scale_max:float, graph_size:ImVec2):nil
    PlotLines = imgui.PlotLines,
    ---@type fun(label:string, values:any, values_count:integer, values_offset:integer, overlay_text:string, scale_min:float, scale_max:float, graph_size:ImVec2, stride:integer):nil
    PlotHistogram = imgui.PlotHistogram,
    ---@type fun(label:string, values_getter:any, data:any, values_count:integer, values_offset:integer, overlay_text:string, scale_min:float, scale_max:float, graph_size:ImVec2):nil
    PlotHistogram = imgui.PlotHistogram,
    ---@type fun(prefix:string, b:bool):nil
    Value = imgui.Value,
    ---@type fun(prefix:string, v:integer):nil
    Value = imgui.Value,
    ---@type fun(prefix:string, v:integer):nil
    Value = imgui.Value,
    ---@type fun(prefix:string, v:float, float_format:string):nil
    Value = imgui.Value,
    ---@type fun():bool
    BeginMenuBar = imgui.BeginMenuBar,
    ---@type fun():nil
    EndMenuBar = imgui.EndMenuBar,
    ---@type fun():bool
    BeginMainMenuBar = imgui.BeginMainMenuBar,
    ---@type fun():nil
    EndMainMenuBar = imgui.EndMainMenuBar,
    ---@type fun(label:string, enabled:bool):bool
    BeginMenu = imgui.BeginMenu,
    ---@type fun():nil
    EndMenu = imgui.EndMenu,
    ---@type fun(label:string, shortcut:string, selected:bool, enabled:bool):bool
    MenuItem = imgui.MenuItem,
    ---@type fun(label:string, shortcut:string, p_selected:any, enabled:bool):bool
    MenuItem = imgui.MenuItem,
    ---@type fun():nil
    BeginTooltip = imgui.BeginTooltip,
    ---@type fun():nil
    EndTooltip = imgui.EndTooltip,
    ---@type fun(fmt:string):nil
    SetTooltip = imgui.SetTooltip,
    ---@type fun(fmt:string, args:va_list):nil
    SetTooltipV = imgui.SetTooltipV,
    ---@type fun(str_id:string, flags:ImGuiWindowFlags):bool
    BeginPopup = imgui.BeginPopup,
    ---@type fun(name:string, p_open:any, flags:ImGuiWindowFlags):bool
    BeginPopupModal = imgui.BeginPopupModal,
    ---@type fun():nil
    EndPopup = imgui.EndPopup,
    ---@type fun(str_id:string, popup_flags:ImGuiPopupFlags):nil
    OpenPopup = imgui.OpenPopup,
    ---@type fun(id:ImGuiID, popup_flags:ImGuiPopupFlags):nil
    OpenPopup = imgui.OpenPopup,
    ---@type fun(str_id:string, popup_flags:ImGuiPopupFlags):nil
    OpenPopupOnItemClick = imgui.OpenPopupOnItemClick,
    ---@type fun():nil
    CloseCurrentPopup = imgui.CloseCurrentPopup,
    ---@type fun(str_id:string, popup_flags:ImGuiPopupFlags):bool
    BeginPopupContextItem = imgui.BeginPopupContextItem,
    ---@type fun(str_id:string, popup_flags:ImGuiPopupFlags):bool
    BeginPopupContextWindow = imgui.BeginPopupContextWindow,
    ---@type fun(str_id:string, popup_flags:ImGuiPopupFlags):bool
    BeginPopupContextVoid = imgui.BeginPopupContextVoid,
    ---@type fun(str_id:string, flags:ImGuiPopupFlags):bool
    IsPopupOpen = imgui.IsPopupOpen,
    ---@type fun(str_id:string, column:integer, flags:ImGuiTableFlags, outer_size:any, inner_width:float):bool
    BeginTable = imgui.BeginTable,
    ---@type fun():nil
    EndTable = imgui.EndTable,
    ---@type fun(row_flags:ImGuiTableRowFlags, min_row_height:float):nil
    TableNextRow = imgui.TableNextRow,
    ---@type fun():bool
    TableNextColumn = imgui.TableNextColumn,
    ---@type fun(column_n:integer):bool
    TableSetColumnIndex = imgui.TableSetColumnIndex,
    ---@type fun(label:string, flags:ImGuiTableColumnFlags, init_width_or_weight:float, user_id:ImGuiID):nil
    TableSetupColumn = imgui.TableSetupColumn,
    ---@type fun(cols:integer, rows:integer):nil
    TableSetupScrollFreeze = imgui.TableSetupScrollFreeze,
    ---@type fun():nil
    TableHeadersRow = imgui.TableHeadersRow,
    ---@type fun(label:string):nil
    TableHeader = imgui.TableHeader,
    ---@type fun():any
    TableGetSortSpecs = imgui.TableGetSortSpecs,
    ---@type fun():integer
    TableGetColumnCount = imgui.TableGetColumnCount,
    ---@type fun():integer
    TableGetColumnIndex = imgui.TableGetColumnIndex,
    ---@type fun():integer
    TableGetRowIndex = imgui.TableGetRowIndex,
    ---@type fun(column_n:integer):string
    TableGetColumnName = imgui.TableGetColumnName,
    ---@type fun(column_n:integer):ImGuiTableColumnFlags
    TableGetColumnFlags = imgui.TableGetColumnFlags,
    ---@type fun(column_n:integer, v:bool):nil
    TableSetColumnEnabled = imgui.TableSetColumnEnabled,
    ---@type fun(target:ImGuiTableBgTarget, color:ImU32, column_n:integer):nil
    TableSetBgColor = imgui.TableSetBgColor,
    ---@type fun(count:integer, id:string, border:bool):nil
    Columns = imgui.Columns,
    ---@type fun():nil
    NextColumn = imgui.NextColumn,
    ---@type fun():integer
    GetColumnIndex = imgui.GetColumnIndex,
    ---@type fun(column_index:integer):float
    GetColumnWidth = imgui.GetColumnWidth,
    ---@type fun(column_index:integer, width:float):nil
    SetColumnWidth = imgui.SetColumnWidth,
    ---@type fun(column_index:integer):float
    GetColumnOffset = imgui.GetColumnOffset,
    ---@type fun(column_index:integer, offset_x:float):nil
    SetColumnOffset = imgui.SetColumnOffset,
    ---@type fun():integer
    GetColumnsCount = imgui.GetColumnsCount,
    ---@type fun(str_id:string, flags:ImGuiTabBarFlags):bool
    BeginTabBar = imgui.BeginTabBar,
    ---@type fun():nil
    EndTabBar = imgui.EndTabBar,
    ---@type fun(label:string, p_open:any, flags:ImGuiTabItemFlags):bool
    BeginTabItem = imgui.BeginTabItem,
    ---@type fun():nil
    EndTabItem = imgui.EndTabItem,
    ---@type fun(label:string, flags:ImGuiTabItemFlags):bool
    TabItemButton = imgui.TabItemButton,
    ---@type fun(tab_or_docked_window_label:string):nil
    SetTabItemClosed = imgui.SetTabItemClosed,
    ---@type fun(auto_open_depth:integer):nil
    LogToTTY = imgui.LogToTTY,
    ---@type fun(auto_open_depth:integer, filename:string):nil
    LogToFile = imgui.LogToFile,
    ---@type fun(auto_open_depth:integer):nil
    LogToClipboard = imgui.LogToClipboard,
    ---@type fun():nil
    LogFinish = imgui.LogFinish,
    ---@type fun():nil
    LogButtons = imgui.LogButtons,
    ---@type fun(fmt:string):nil
    LogText = imgui.LogText,
    ---@type fun(fmt:string, args:va_list):nil
    LogTextV = imgui.LogTextV,
    ---@type fun(flags:ImGuiDragDropFlags):bool
    BeginDragDropSource = imgui.BeginDragDropSource,
    ---@type fun(type:string, data:any, sz:size_t, cond:ImGuiCond):bool
    SetDragDropPayload = imgui.SetDragDropPayload,
    ---@type fun():nil
    EndDragDropSource = imgui.EndDragDropSource,
    ---@type fun():bool
    BeginDragDropTarget = imgui.BeginDragDropTarget,
    ---@type fun(type:string, flags:ImGuiDragDropFlags):any
    AcceptDragDropPayload = imgui.AcceptDragDropPayload,
    ---@type fun():nil
    EndDragDropTarget = imgui.EndDragDropTarget,
    ---@type fun():any
    GetDragDropPayload = imgui.GetDragDropPayload,
    ---@type fun(clip_rect_min:any, clip_rect_max:any, intersect_with_current_clip_rect:bool):nil
    PushClipRect = imgui.PushClipRect,
    ---@type fun():nil
    PopClipRect = imgui.PopClipRect,
    ---@type fun():nil
    SetItemDefaultFocus = imgui.SetItemDefaultFocus,
    ---@type fun(offset:integer):nil
    SetKeyboardFocusHere = imgui.SetKeyboardFocusHere,
    ---@type fun(flags:ImGuiHoveredFlags):bool
    IsItemHovered = imgui.IsItemHovered,
    ---@type fun():bool
    IsItemActive = imgui.IsItemActive,
    ---@type fun():bool
    IsItemFocused = imgui.IsItemFocused,
    ---@type fun(mouse_button:ImGuiMouseButton):bool
    IsItemClicked = imgui.IsItemClicked,
    ---@type fun():bool
    IsItemVisible = imgui.IsItemVisible,
    ---@type fun():bool
    IsItemEdited = imgui.IsItemEdited,
    ---@type fun():bool
    IsItemActivated = imgui.IsItemActivated,
    ---@type fun():bool
    IsItemDeactivated = imgui.IsItemDeactivated,
    ---@type fun():bool
    IsItemDeactivatedAfterEdit = imgui.IsItemDeactivatedAfterEdit,
    ---@type fun():bool
    IsItemToggledOpen = imgui.IsItemToggledOpen,
    ---@type fun():bool
    IsAnyItemHovered = imgui.IsAnyItemHovered,
    ---@type fun():bool
    IsAnyItemActive = imgui.IsAnyItemActive,
    ---@type fun():bool
    IsAnyItemFocused = imgui.IsAnyItemFocused,
    ---@type fun():ImVec2
    GetItemRectMin = imgui.GetItemRectMin,
    ---@type fun():ImVec2
    GetItemRectMax = imgui.GetItemRectMax,
    ---@type fun():ImVec2
    GetItemRectSize = imgui.GetItemRectSize,
    ---@type fun():nil
    SetItemAllowOverlap = imgui.SetItemAllowOverlap,
    ---@type fun():any
    GetMainViewport = imgui.GetMainViewport,
    ---@type fun(size:any):bool
    IsRectVisible = imgui.IsRectVisible,
    ---@type fun(rect_min:any, rect_max:any):bool
    IsRectVisible = imgui.IsRectVisible,
    ---@type fun():number
    GetTime = imgui.GetTime,
    ---@type fun():integer
    GetFrameCount = imgui.GetFrameCount,
    ---@type fun():any
    GetBackgroundDrawList = imgui.GetBackgroundDrawList,
    ---@type fun():any
    GetForegroundDrawList = imgui.GetForegroundDrawList,
    ---@type fun():any
    GetDrawListSharedData = imgui.GetDrawListSharedData,
    ---@type fun(idx:ImGuiCol):string
    GetStyleColorName = imgui.GetStyleColorName,
    ---@type fun(storage:any):nil
    SetStateStorage = imgui.SetStateStorage,
    ---@type fun():any
    GetStateStorage = imgui.GetStateStorage,
    ---@type fun(items_count:integer, items_height:float, out_items_display_start:any, out_items_display_end:any):nil
    CalcListClipping = imgui.CalcListClipping,
    ---@type fun(id:ImGuiID, size:any, flags:ImGuiWindowFlags):bool
    BeginChildFrame = imgui.BeginChildFrame,
    ---@type fun():nil
    EndChildFrame = imgui.EndChildFrame,
    ---@type fun(text:string, text_end:string, hide_text_after_double_hash:bool, wrap_width:float):ImVec2
    CalcTextSize = imgui.CalcTextSize,
    ---@type fun(in:ImU32):ImVec4
    ColorConvertU32ToFloat4 = imgui.ColorConvertU32ToFloat4,
    ---@type fun(in:any):ImU32
    ColorConvertFloat4ToU32 = imgui.ColorConvertFloat4ToU32,
    ---@type fun(r:float, g:float, b:float, out_h:any, out_s:any, out_v:any):nil
    ColorConvertRGBtoHSV = imgui.ColorConvertRGBtoHSV,
    ---@type fun(h:float, s:float, v:float, out_r:any, out_g:any, out_b:any):nil
    ColorConvertHSVtoRGB = imgui.ColorConvertHSVtoRGB,
    ---@type fun(imgui_key:ImGuiKey):integer
    GetKeyIndex = imgui.GetKeyIndex,
    ---@type fun(user_key_index:integer):bool
    IsKeyDown = imgui.IsKeyDown,
    ---@type fun(user_key_index:integer, repeat:bool):bool
    IsKeyPressed = imgui.IsKeyPressed,
    ---@type fun(user_key_index:integer):bool
    IsKeyReleased = imgui.IsKeyReleased,
    ---@type fun(key_index:integer, repeat_delay:float, rate:float):integer
    GetKeyPressedAmount = imgui.GetKeyPressedAmount,
    ---@type fun(want_capture_keyboard_value:bool):nil
    CaptureKeyboardFromApp = imgui.CaptureKeyboardFromApp,
    ---@type fun(button:ImGuiMouseButton):bool
    IsMouseDown = imgui.IsMouseDown,
    ---@type fun(button:ImGuiMouseButton, repeat:bool):bool
    IsMouseClicked = imgui.IsMouseClicked,
    ---@type fun(button:ImGuiMouseButton):bool
    IsMouseReleased = imgui.IsMouseReleased,
    ---@type fun(button:ImGuiMouseButton):bool
    IsMouseDoubleClicked = imgui.IsMouseDoubleClicked,
    ---@type fun(r_min:any, r_max:any, clip:bool):bool
    IsMouseHoveringRect = imgui.IsMouseHoveringRect,
    ---@type fun(mouse_pos:any):bool
    IsMousePosValid = imgui.IsMousePosValid,
    ---@type fun():bool
    IsAnyMouseDown = imgui.IsAnyMouseDown,
    ---@type fun():ImVec2
    GetMousePos = imgui.GetMousePos,
    ---@type fun():ImVec2
    GetMousePosOnOpeningCurrentPopup = imgui.GetMousePosOnOpeningCurrentPopup,
    ---@type fun(button:ImGuiMouseButton, lock_threshold:float):bool
    IsMouseDragging = imgui.IsMouseDragging,
    ---@type fun(button:ImGuiMouseButton, lock_threshold:float):ImVec2
    GetMouseDragDelta = imgui.GetMouseDragDelta,
    ---@type fun(button:ImGuiMouseButton):nil
    ResetMouseDragDelta = imgui.ResetMouseDragDelta,
    ---@type fun():ImGuiMouseCursor
    GetMouseCursor = imgui.GetMouseCursor,
    ---@type fun(cursor_type:ImGuiMouseCursor):nil
    SetMouseCursor = imgui.SetMouseCursor,
    ---@type fun(want_capture_mouse_value:bool):nil
    CaptureMouseFromApp = imgui.CaptureMouseFromApp,
    ---@type fun():string
    GetClipboardText = imgui.GetClipboardText,
    ---@type fun(text:string):nil
    SetClipboardText = imgui.SetClipboardText,
    ---@type fun(ini_filename:string):nil
    LoadIniSettingsFromDisk = imgui.LoadIniSettingsFromDisk,
    ---@type fun(ini_data:string, ini_size:size_t):nil
    LoadIniSettingsFromMemory = imgui.LoadIniSettingsFromMemory,
    ---@type fun(ini_filename:string):nil
    SaveIniSettingsToDisk = imgui.SaveIniSettingsToDisk,
    ---@type fun(out_ini_size:any):string
    SaveIniSettingsToMemory = imgui.SaveIniSettingsToMemory,
    ---@type fun(version_str:string, sz_io:size_t, sz_style:size_t, sz_vec2:size_t, sz_vec4:size_t, sz_drawvert:size_t, sz_drawidx:size_t):bool
    DebugCheckVersionAndDataLayout = imgui.DebugCheckVersionAndDataLayout,
    ---@type fun(alloc_func:ImGuiMemAllocFunc, free_func:ImGuiMemFreeFunc, user_data:any):nil
    SetAllocatorFunctions = imgui.SetAllocatorFunctions,
    ---@type fun(p_alloc_func:any, p_free_func:any, p_user_data:any):nil
    GetAllocatorFunctions = imgui.GetAllocatorFunctions,
    ---@type fun(size:size_t):any
    MemAlloc = imgui.MemAlloc,
    ---@type fun(ptr:any):nil
    MemFree = imgui.MemFree,
    ---@type fun(label:string, items_count:integer, height_in_items:integer):bool
    ListBoxHeader = imgui.ListBoxHeader,
    ---@type fun(label:string, data_type:ImGuiDataType, p_data:any, v_speed:float, p_min:any, p_max:any, format:string, power:float):bool
    DragScalar = imgui.DragScalar,
    ---@type fun(label:string, data_type:ImGuiDataType, p_data:any, components:integer, v_speed:float, p_min:any, p_max:any, format:string, power:float):bool
    DragScalarN = imgui.DragScalarN,
    ---@type fun(label:string, data_type:ImGuiDataType, p_data:any, p_min:any, p_max:any, format:string, power:float):bool
    SliderScalar = imgui.SliderScalar,
    ---@type fun(label:string, data_type:ImGuiDataType, p_data:any, components:integer, p_min:any, p_max:any, format:string, power:float):bool
    SliderScalarN = imgui.SliderScalarN,
}
-----------------------------------------------------------------------------
-- glad.dll
-----------------------------------------------------------------------------
---@type Table<string, any>
local glad = ffi.load('glad')
M.cache.glad = glad
M.libs.glad = {
    ---@type fun(load:GLADuserptrloadfunc, userptr:any):integer
    gladLoadGLUserPtr = glad.gladLoadGLUserPtr,
    ---@type fun(load:GLADloadfunc):integer
    gladLoadGL = glad.gladLoadGL,
}
return M
